version: '3'

volumes:
  redis_data: {}

services:
  redis:
    image: bitnami/redis
    container_name: redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data
